version: '3'
services:
  yii2-app:
    image: aman435/yii2-app:latest
    expose:
      - "9000"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - yii2-app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

