version: '3'
services:
  yii2-app:
    image: aman435/yii2-app
    ports:
      - "9000:80"
    deploy:
      replicas: 1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000"]
      interval: 30s
      retries: 3
