name: Deploy Yii2 App via Docker Swarm

on:
  push:
    branches:
      - main  # change if you're using a different branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/yii2-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/yii2-app:latest

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/yii2-app:latest
            docker service ls | grep yii2-app-service && \
              docker service update --image ${{ secrets.DOCKER_USERNAME }}/yii2-app:latest yii2-app-service || \
              docker service create --name yii2-app-service -p 9000:9000 ${{ secrets.DOCKER_USERNAME }}/yii2-app:latest
